name: CI Web Main

on:
  push:
    branches:
      - main

jobs:
  dist:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - run: zip -r deploy.zip .next tsconfig.json yarn.lock package.json public

      - name: Copy to Main Machine
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: "deploy.zip"
          target: "~/code/openheal/web"

      - name: Multiple Command on AWS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ~/code/openheal/web
            pm2 stop openheal_web_main
            unzip -o deploy.zip
            yarn install --production
            rm -rf deploy.zip
            pm2 start openheal_web_main
